### ISSUE TITLE
ERROR: /sbin/rpc.statd failed

### ISSUE THREAD

**Issue by domalex** [obeone/docker-nfs-server#4]
When running the image, the server it is terminated with the above mentioned message. It would be great you could fix that.

I am happy you forked the original project and keep it up to date. I tried to do it myself but was not able to do so. It is just way above my capabilities.

- Raspberry Pi 3 B+
- Archlinux ARM/64 (AArch64)

Thank you

Dominik

**Comment by xZero707** [comment]
The error occurs with Alpine versions above 3.15. See issue N0rthernL1ghts/docker-nfs-server#3.

Check my independent fork for working build: [N0rthernL1ghts/docker-nfs-server](https://github.com/N0rthernL1ghts/docker-nfs-server).

If you want to do that manually, you need to build the image yourself with some changes to the Dockerfile. You can see the commit history in my fork for more info.

**Comment by domalex** [comment]
Thank you for the explanations. I will try it with alpine 3.15.

Nevertheless, I think the error should be fixed. Other users of the repository will stumble upon the same problem.

**Comment by obeone** [comment]
Sorry, I missed this issue too... Duplicated with #7.

I publish right now the correction (I wasn't using this image anymore, but I need it again !)
