### ISSUE TITLE
2: Unsupported version (on amd64)

### ISSUE THREAD

**Issue by klauserber** [obeone/docker-nfs-server#7]
Hello, are there any plans to apply this patch?

https://github.com/mheers/docker-nfs-server/commit/ae65d1559fc22f96c28eec2845b3c50979e6694b

https://github.com/ehough/docker-nfs-server/issues/76

We get this error in our environment, which is amd64. Seems to be not a arm64-only problem. The image mheers/nfs-server fixes the issue.

We are in the IONOS cloud, the k8s nodes are running Ubuntu 20.04.5 LTS.

**Comment by obeone** [comment]
Hi,
I missed this issue… Working on it !

**Comment by obeone** [comment]
Fixed in #9
